# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    view:
        view_response_listener: 'force'
        formats:
            json: true
            html: true
    exception:
        flatten_exception_format: legacy
    format_listener:
        rules:
            - { path: ^/api/doc, prefer_extension: true, fallback_format: html, priorities: [ html ] }
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
